### ISSUE TITLE
Examples for tracking

### ISSUE THREAD

**Issue by geekyme** [HubSpot/react-experiments#14]
Would love to see how each variation chosen by planout can be instrumented with tracking tools such as GA or Amplitude.

**Comment by rawls238** [comment]
This is a great idea; it would good to have cookbook examples integrating with the most popular third-party analytics libraries. I'll try to do this sometime tomorrow

**Comment by geekyme** [comment]
:+1: looking forward to this

**Comment by geekyme** [comment]
Another concern @rawls238 is will running all these experiments result in additional processing overhead? I know that react is particularly bad at server side rendering already so all these dynamic assignments of user_ids to variations would add on more overhead?

**Comment by rawls238** [comment]
It shouldn't, at least not from our experience. We've been using PlanOut.js in production (in a client-side app) for a few months now and generally assignment usually takes between 0-5ish ms but usually closer to 0ms. Under the hood it's just doing a bunch of hashing which naturally is rather quick.

This react library hasn't been as tested in production settings as it's still relatively new. However, I've found it to be rather fast with very minimal overhead. If you run into any performance concerns please let us know as most of the operations done by PlanOut.js + react-experiments should be very lightweight and any noticeable performance impact most likely would be coming from a bug of some sort.

**Comment by geekyme** [comment]
Cool ok. Let's see how u set up ur tracking :p

**Comment by rawls238** [comment]
I added examples of using Mixpanel / Amplitude / GA for the log function in the README of PlanOut.js (https://github.com/HubSpot/PlanOut.js/pull/19). Let me know if you run into any issues @geekyme
