### ISSUE TITLE
tracking for single page app?

### ISSUE THREAD

**Issue by jacobcantele** [HubSpot/react-experiments#18]
Is there anything in react-experiments that would help us with page tracking on a single page app? We are desperately needing asynchronous page tracking.

**Comment by gusvargas** [comment]
Hey @jacobcantele,

Can you please describe more in detail what you're trying to do? Are you trying to run an A/B test with tracking or are you trying to figure out how to do async analytics tracking with google analytics, crazyegg, twitter, etc. within a SPA?

**Comment by jacobcantele** [comment]
gusvargas,

We have an SPA where we need to be able to use HubSpot Page Tracking to update the individual contacts' record with all of the Page Views of the specific contact and their activity on the website. On the main HubSpot developer forum, they are saying that asynchronous Page Tracking is not supported, and that we have to instead us custom Events. This won't work for us, because our entire HubSpot environment is built to be trigger workflows around Page Views.

I was hoping there was something in react-experiments that could help, or anything else you know of, honestly.

**Comment by gusvargas** [comment]
Hmm. Sorry, but I don't think this project is going to get to any closer to what you're trying to accomplish. `react-experiments` provides abstractions for creating bindings between [PlanOut.js](https://github.com/HubSpot/PlanOut.js/) experiments (or experiment definitions that share a similar interface) and React components.

@geekjuice, do you have any advice here?

**Comment by geekjuice** [comment]
Hey @jacobcantele,

Since this seems outside of the scope of this project, feel free to email me directly at `nhwang@hubspot.com` and we can discuss in a private thread. :+1:

**Comment by corbanb** [comment]
@geekjuice and @gusvargas was there any movement on this?

**Comment by gusvargas** [comment]
@corbanb No, there wasn't any planed movement here since the requested functionality is outside the scope of this project.

As mentioned above, the purpose of this project is to bind React components to your PlanOut.js (or similar) experiments to automate the process of injecting experiment params and logging exposure. 

If you're problem is that you need need to asynchronously fire tracking events with trackers that do not support async tracking then this project will not help.
