### ISSUE TITLE
error/warnings loading example

### ISSUE THREAD

**Issue by brandonmp** [HubSpot/react-experiments#20]
cloned, npm install, ran build.sh, then opened examples/index.html--it may be something trivial since I'm pretty inexperienced, but hoping someone has dealt w/ this before.

![image](https://cloud.githubusercontent.com/assets/14139991/13517162/dff66670-e18e-11e5-82b9-3d2724a3dd5c.png)

**Comment by brandonmp** [comment]
Uncaught TypeError: Cannot read property 'foo' of undefinedReact.createClass.render @ Inline JSX script:31ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ react-with-addons.js:7445ReactCompositeComponentMixin._renderValidatedComponent @ react-with-addons.js:7472wrapper @ react-with-addons.js:13970ReactCompositeComponentMixin.mountComponent @ react-with-addons.js:6893wrapper @ react-with-addons.js:13970ReactReconciler.mountComponent @ react-with-addons.js:14781ReactMultiChild.Mixin.mountChildren @ react-with-addons.js:13414ReactDOMComponent.Mixin._createContentMarkup @ react-with-addons.js:8207ReactDOMComponent.Mixin.mountComponent @ react-with-addons.js:8117ReactReconciler.mountComponent @ react-with-addons.js:14781ReactCompositeComponentMixin.mountComponent @ react-with-addons.js:6903wrapper @ react-with-addons.js:13970ReactReconciler.mountComponent @ react-with-addons.js:14781ReactCompositeComponentMixin.mountComponent @ react-with-addons.js:6903wrapper @ react-with-addons.js:13970ReactReconciler.mountComponent @ react-with-addons.js:14781ReactCompositeComponentMixin.mountComponent @ react-with-addons.js:6903wrapper @ react-with-addons.js:13970ReactReconciler.mountComponent @ react-with-addons.js:14781ReactMultiChild.Mixin.mountChildren @ react-with-addons.js:13414ReactDOMComponent.Mixin._createContentMarkup @ react-with-addons.js:8207ReactDOMComponent.Mixin.mountComponent @ react-with-addons.js:8117ReactReconciler.mountComponent @ react-with-addons.js:14781ReactCompositeComponentMixin.mountComponent @ react-with-addons.js:6903wrapper @ react-with-addons.js:13970ReactReconciler.mountComponent @ react-with-addons.js:14781ReactMultiChild.Mixin.mountChildren @ react-with-addons.js:13414ReactDOMComponent.Mixin._createContentMarkup @ react-with-addons.js:8207ReactDOMComponent.Mixin.mountComponent @ react-with-addons.js:8117ReactReconciler.mountComponent @ react-with-addons.js:14781ReactCompositeComponentMixin.mountComponent @ react-with-addons.js:6903wrapper @ react-with-addons.js:13970ReactReconciler.mountComponent @ react-with-addons.js:14781ReactCompositeComponentMixin.mountComponent @ react-with-addons.js:6903wrapper @ react-with-addons.js:13970ReactReconciler.mountComponent @ react-with-addons.js:14781mountComponentIntoNode @ react-with-addons.js:12581Mixin.perform @ react-with-addons.js:18402batchedMountComponentIntoNode @ react-with-addons.js:12602Mixin.perform @ react-with-addons.js:18402ReactDefaultBatchingStrategy.batchedUpdates @ react-with-addons.js:9669batchedUpdates @ react-with-addons.js:16633ReactMount._renderNewRootComponent @ react-with-addons.js:12737wrapper @ react-with-addons.js:13970ReactMount.render @ react-with-addons.js:12826wrapper @ react-with-addons.js:13970(anonymous function) @ Inline JSX script:82run @ JSXTransformer.js:184check @ JSXTransformer.js:238loadScripts @ JSXTransformer.js:291runScripts @ JSXTransformer.js:320

**Comment by rawls238** [comment]
Possible I didn't update the demo when upgrading the version of react. I'll take a look at this tomorrow morning

**Comment by rawls238** [comment]
@brandonmp thanks again for reporting this, should be fixed now from https://github.com/HubSpot/react-experiments/commit/5f5a8e60e7c966243e1a6a17526dc56c6647df5a. The example was using an older version of React.

Let me know if you run into any other issues!

**Comment by brandonmp** [comment]
awesome-thanks for the quick response @rawls238 , stoked to start using this in my project
